Update to more recent version of dropwizard.io metrics module
The one API breaking change affected ParfaitReporterFactoryTest,
relatively straightforward to resolve by using the metrics class
YamlConfigurationFactory (ConfigurationFactory now an interface).

That caused this fallout...

testBuildFromYamlConfiguration(io.pcp.parfait.dropwizard.ParfaitReporterFactoryTest)  Time elapsed: 0.123 sec  <<< ERROR!
io.dropwizard.configuration.ConfigurationParsingException: /home/source/git/parfait/parfait-dropwizard/target/test-classes/io/pcp/parfait/dropwizard/metric-app.yml has an error:
  * Failed to parse configuration at: reporters.excludes; (was java.lang.NullPointerException) (through reference chain: io.dropwizard.metrics.MetricsFactory["reporters"]->io.pcp.parfait.dropwizard.ParfaitReporterFactory["excludes"])

...which is resolved here by no longer having an empty "excludes"
section in the metrics-app test YAML configuration file.