Fix ThreadContextTest failures for some log4j versions
(#1) Failed tests:
  ThreadContextTest.testClearRemovesMDCValue:78 Expected: <null> but was: {}
(#2) Failed tests:
  ThreadContextTest.testClearRemovesMDCValue:89 expected:<0> but was:<1>
  (some debugging finds the {painter=7} hash entry to still be present)

Evidently the newMDCEnabledContext() in log4j ThreadContext
returns an empty hash for some versions, not null (case #1).
It also seems that different deep/shallow ThreadContext hash
copying behaviours can cause the test to fail (case #2).